# Generated by Django 3.2.25 on 2024-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20240628_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='volunteer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
